
# Copyright (C) 2020 Istituto Italiano di Tecnologia (IIT). All rights reserved.
# This software may be modified and distributed under the terms of the
# GNU Lesser General Public License v2.1 or any later version.

get_property(umbrella_includes_list GLOBAL PROPERTY umbrella_includes)
get_property(target_list GLOBAL PROPERTY iCubTorqueControl_TARGETS)

configure_file("${CMAKE_CURRENT_SOURCE_DIR}/cmake/TorqueControlApplications.h.in"
               "${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/iCubTorqueControl/TorqueControlApplications.h" @ONLY)

install(FILES "${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/iCubTorqueControl/TorqueControlApplications.h"
       DESTINATION "${CMAKE_INSTALL_INCLUDEDIR}/iCubTorqueControl")

add_library(TorqueControlApplications INTERFACE)
target_compile_features(TorqueControlApplications INTERFACE cxx_std_17)
target_link_libraries(TorqueControlApplications INTERFACE ${target_list})
target_include_directories(TorqueControlApplications INTERFACE "$<BUILD_INTERFACE:${CMAKE_CURRENT_BINARY_DIR}/Autogenerated/iCubTorqueControl/TorqueControlApplications.h>"
  "$<INSTALL_INTERFACE:$<INSTALL_PREFIX>/${CMAKE_INSTALL_INCLUDEDIR}>")

# Specify installation targets, typology and destination folders.
install(TARGETS        TorqueControlApplications
  EXPORT               ${PROJECT_NAME}
  COMPONENT            runtime)

add_library(iCubTorqueControl::TorqueControlApplications ALIAS TorqueControlApplications)
set_property(GLOBAL APPEND PROPERTY iCubTorqueControl_TARGETS TorqueControlApplications)
